server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://34.80.99.159:3306/jjc?useSSL=false&useUniCode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#  devtools:
#    restart:
#      enabled: true
  url:
#    base: http://localhost:8080
#    base: http://k02d1051.p.ssafy.io:8080
    base: http://www.jjcake.co.kr:8080
    base-path: /home/ubuntu/
    user-profile: image/profile/
    user-order: image/order/
    user-portfilo: image/portfolio/
    user-review: image/review/
#  profiles: local
  redis:
    port: 6379
    host: localhost
    prefix:
      id: LOGOUT_USER
  jwt:
    secret: mozzi
    header-name: X-AUTH-TOKEN
  messages:
    basename: i18n/exception
    encoding: UTF-8
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: file:/home/ubuntu
    add-mappings: true


mybatis:
  type-aliases-package: com.ssafy.vo
  mapper-locations: mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null